/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter and paginate */
        get: operations["listComplaints"];
        put?: never;
        /** Validate, triage, persist */
        post: operations["createComplaint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/complaints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getComplaint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/complaints/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance status through the state machine */
        patch: operations["updateComplaintStatus"];
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregates by category and priority */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active triage provider and last 20 outcomes */
        get: operations["getProviderMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Category: "water" | "electricity" | "sanitation" | "roads" | "streetlights" | "other";
        /** @enum {string} */
        Priority: "high" | "normal" | "low";
        /** @enum {string} */
        Status: "open" | "in_progress" | "resolved" | "rejected";
        ComplaintCreate: {
            /** @description Free-text complaint */
            text: string;
            location: string;
            /** @description Optional email or phone */
            reporter_contact?: string | null;
        };
        Complaint: {
            /** Format: uuid */
            id: string;
            text: string;
            location: string;
            reporter_contact?: string | null;
            category: components["schemas"]["Category"];
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["Status"];
            ai_summary?: string | null;
            /**
             * @description Which provider decided this triage
             * @enum {string}
             */
            triaged_by: "llm:groq" | "llm:ollama" | "rules" | "rules:fallback";
            triage_latency_ms: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ComplaintPage: {
            items: components["schemas"]["Complaint"][];
            total: number;
            page: number;
            page_size: number;
        };
        StatusUpdate: {
            status: components["schemas"]["Status"];
        };
        Stats: {
            total: number;
            by_category: {
                [key: string]: number;
            };
            by_priority: {
                [key: string]: number;
            };
        };
        TriageOutcome: {
            provider: string;
            latency_ms: number;
            fallback: boolean;
            /** Format: uuid */
            complaint_id?: string | null;
        };
        ProviderMeta: {
            active_provider: string;
            recent_triages: components["schemas"]["TriageOutcome"][];
        };
        ValidationError: {
            detail: {
                field: string;
                message: string;
            }[];
        };
        Error: {
            detail: string;
        };
        Ready: {
            /** @enum {string} */
            status: "ok" | "degraded";
            dependencies: {
                postgres?: boolean;
                redis?: boolean;
            };
        };
    };
    responses: {
        /** @description Field-level validation failure */
        FieldErrors: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
        /** @description Rate limit exceeded — see Retry-After header */
        RateLimited: {
            headers: {
                /** @description Seconds to wait */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid status transition — detail names the attempted transition */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        category: components["schemas"]["Category"];
        priority: components["schemas"]["Priority"];
        status: components["schemas"]["Status"];
        page: number;
        page_size: number;
        id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listComplaints: {
        parameters: {
            query?: {
                category?: components["parameters"]["category"];
                priority?: components["parameters"]["priority"];
                status?: components["parameters"]["status"];
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["page_size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of complaints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintPage"];
                };
            };
            400: components["responses"]["FieldErrors"];
        };
    };
    createComplaint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Complaint"];
                };
            };
            400: components["responses"]["FieldErrors"];
            429: components["responses"]["RateLimited"];
        };
    };
    getComplaint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Complaint"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateComplaintStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Complaint"];
                };
            };
            400: components["responses"]["FieldErrors"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: {
                /** @description Response header: cache state (always present) */
                "X-Cache"?: "HIT" | "MISS";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    getProviderMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observability surface */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMeta"];
                };
            };
        };
    };
}
