# 34 seed complaints, tuple order: category, priority, location, text.
# Realistic Urdu-influenced English; spread across all six categories.
SEED_COMPLAINTS: list[tuple[str, str, str, str]] = [
    ("water", "high", "Street 12, Model Town", "Burst water main flooding Street 12 since fajr, water entering ground floors"),
    ("water", "normal", "Block C, Sector 4", "Pani ki supply band hai 3 din se, tanker mangwana par raha hai, please check the line"),
    ("water", "normal", "Gali 5, Mohalla Rehmat", "Tap water is coming muddy and smells bad since yesterday, we are boiling it before use"),
    ("water", "low", "Near Jamia Masjid", "Small leak at the public tap near the masjid, dripping all day but not urgent"),
    ("water", "high", "Govt. Girls School Road", "Main pipeline near the school cracked, road is under water and vans cannot pass"),
    ("water", "normal", "Street 3, Green Town", "Water pressure is very low in the whole gali since the new tubewell started"),
    ("electricity", "high", "Main Bazaar", "Live wire hanging low on Main Bazaar after the storm, kids play here, very dangerous"),
    ("electricity", "high", "Petrol Pump Chowk", "Transformer sparking and smoking near the petrol pump, please send the line staff at once"),
    ("electricity", "normal", "Block C, Sector 4", "Bijli 8 hours gayab every day in Block C, load shedding is beyond the schedule"),
    ("electricity", "normal", "Street 9, Green Town", "Voltage fluctuation is burning our fridges and fans, third time this month"),
    ("electricity", "low", "House 44, Street 6", "Meter reading not taken for two months, bill is coming on average, please fix"),
    ("electricity", "high", "Graveyard Road", "Power pole leaning on the side of the graveyard road after a truck hit it"),
    ("sanitation", "high", "Outside Civil Dispensary", "Sewage overflowing on the street outside the dispensary, smell is unbearable and it is entering shops"),
    ("sanitation", "normal", "Park Gate, Sector 2", "Kachra has not been picked up for a week, heap is growing near the park gate"),
    ("sanitation", "normal", "Street 7, Model Town", "Gutter is blocked on Street 7, dirty water standing and mosquitoes everywhere"),
    ("sanitation", "low", "Main Market Corner", "Please put a dustbin at the corner of the market, people throw garbage on the road"),
    ("sanitation", "high", "Bus Stop, GT Road", "Open manhole without cover near the bus stop, someone will fall inside"),
    ("sanitation", "normal", "Gali 2, Mohalla Rehmat", "Nali ka pani ghar ke saamne jama hai, sweeper has not come since Monday"),
    ("roads", "high", "Bridge Approach, Canal Road", "Huge pothole on the bridge approach caused a bike accident this morning, needs urgent repair"),
    ("roads", "normal", "Street 8, Green Town", "Road outside our gali was dug for the gas pipe and never filled back, cars are getting stuck"),
    ("roads", "normal", "Govt. Boys School Gate", "Speed breaker is too high near the school gate, vehicles scrape and children get hurt"),
    ("roads", "low", "Chowk Nishtar", "Faded zebra crossing at the chowk, please repaint when budget allows"),
    ("roads", "normal", "Main Market", "Footpath tiles are broken all along the market, elderly people cannot walk safely"),
    ("roads", "high", "Canal Bank Road", "Road caved in after the rain near the canal, there is a hole big enough for a car"),
    ("streetlights", "normal", "Street 9, Model Town", "Street light pole number 14 on Street 9 is off for two weeks, area is very dark at night"),
    ("streetlights", "high", "Highway Link Road", "All streetlights are off on the link road and there were two snatching incidents this week"),
    ("streetlights", "normal", "Sector 2 Park", "Street lights stay on during the day and waste electricity, the timer seems broken"),
    ("streetlights", "low", "Park Bench, Sector 2", "One bulb is flickering near the park bench, please replace when you are passing"),
    ("streetlights", "normal", "Gali 7, Mohalla Rehmat", "Andhera hai poori gali mein, street lights not working since the transformer was changed"),
    ("streetlights", "normal", "New Housing Scheme", "New street lights were installed but never switched on near the housing scheme"),
    ("other", "normal", "Graveyard Road", "Stray dogs are attacking motorcyclists near the graveyard, please arrange something"),
    ("other", "low", "Front of National Bank", "Hand carts are blocking the footpath in front of the bank every evening"),
    ("other", "normal", "Marriage Hall, Sector 5", "Noise from the marriage hall continues after midnight every weekend, we cannot sleep"),
    ("other", "low", "Union Council Office", "Please provide a suggestion box or a helpline number at the union council office"),
]
